Add function: update password
youngmonkeys/freechat pull request #15
Opened 2021-04-26 14:11 UTC by vu-luong

- Add text in LoginView: "Just login, register automatically"
- Add `update password` function

2021-04-26 15:53 UTC, tvd12 requested changes
@vu-luong
PLTAL

2021-04-26 15:53 UTC, tvd12 commented on reactjs/src/views/LoginView/LoginView.jsx
> +                        </div>
Anh nghĩ là để sau nút login và căn giữa sẽ hợp lý hơn, và nên thêm dấu chấm than thể hiện sự chú ý!
```
Just login, register automatically
```

2021-04-26 15:53 UTC, tvd12 commented on reactjs/src/views/MessageView/MessageView.jsx
> +                                            <span className="dropdown-item" href="#">Another action</span>
`Another action` hiện tại không có chức năng gì thì bỏ đi em ạ

2021-04-26 15:53 UTC, tvd12 commented on reactjs/src/views/MessageView/MessageView.jsx
> +                                    <div class="dropdown">
Phải dùng className em ạ, nó đang báo lỗi:
```javascript
Warning: Invalid DOM property `class`. Did you mean `className`?
```

2021-04-26 15:53 UTC, tvd12 commented on server/freechat-api/src/main/java/com/tvd12/freechat/handler/ChatUpdatePasswordHandler.java
> +    }
Khi đã ném `EzyBadRequestException` rồi thì hàm này sẽ thừa

2021-04-26 15:53 UTC, tvd12 commented on server/freechat-api/src/main/java/com/tvd12/freechat/handler/ChatUpdatePasswordHandler.java
> +        data.add("Successfully updated password!");
nếu đã ném exception, thì không cần data em ạ

2021-04-26 15:53 UTC, tvd12 commented on reactjs/src/socket/SocketProxy.js
> +
Đoạn này sẽ là:
````javascript
setupApp.addDataHandler(Command.UPDATE_PASSWORD, function (app, data) {
            // data: [STATUS, MESSAGE], e.g., ["error", "Wrong old password"]
            console.log("handle update user password: " + JSON.stringify(data))
            updatePasswordController.updateViews("updatePasswordSuccess", data[1]);
            updatePasswordController.updateViews("doneUpdatePassword", null);
        });
        setupApp.addDataHandler(Command.ERROR, function (app, data) {
            let errorCoce = data[0];
            if (errorCoce == ErrorCodes.WRONG_PASSWORD) {
                updatePasswordController.updateViews("updatePasswordError", data[1]);
            }
        });
````

2021-04-26 15:53 UTC, tvd12 commented on reactjs/src/socket/SocketConstants.js
> +export const SOCKET_URL = "ws://localhost:2208/ws";
Bổ sung:
````javascript
export const ErrorCodes = {
    WRONG_PASSWORD: 5
}
````

2021-04-26 15:53 UTC, tvd12 commented on reactjs/src/index.js
> +import 'bootstrap/dist/js/bootstrap.bundle.min';
Anh thấy cách sử dụng này hơi lạ lạ, anh hay tham khảo ở đây: https://react-bootstrap.github.io/getting-started/introduction

2021-04-26 15:53 UTC, tvd12 commented on reactjs/src/socket/SocketConstants.js
> +    UPDATE_PASSWORD: '11'
Thêm: `ERROR: 'err'` vào đầu hoặc cuối

2021-04-26 23:16 UTC, vu-luong commented on reactjs/src/index.js
> +import 'bootstrap/dist/js/bootstrap.bundle.min';
1. Em thấy anh đang download file bootstrap.css về xong import vào `import './css/bootstrap.css'`, không giống trong link anh gửi hướng dẫn:
![image](https://user-images.githubusercontent.com/8142030/116162452-2921fd80-a739-11eb-9f01-da18bf243f41.png)

2. Do thằng dropdown của bootstrap dùng thư viện Popper.js nên em preload thêm thằng Popper.

2021-04-26 23:26 UTC, vu-luong commented
@tvd12 Please review my latest commit!

2021-04-27 14:35 UTC, tvd12 approved these changes
LGTM

2021-04-27 14:35 UTC, merged