Features/update handle chat user
youngmonkeys/freechat pull request #21
Opened 2021-07-18 14:22 UTC by toilahtc96

update handle chat user and add repo for chat user token firebase

2021-08-04 16:49 UTC, tvd12 requested changes
@toilahtc96 PLTAL

2021-08-04 16:49 UTC, tvd12 commented on .gitignore
> +swift/
tại sao em muốn bỏ thư mục swift em nhỉ?

2021-08-04 16:49 UTC, tvd12 commented on server/freechat-api/src/main/java/com/tvd12/freechat/handler/ChatUserMessageHandler.java
> +
anh nghĩ đoạn này không cần thiết phải format lại code, vì code đó đã chạy ổn định rồi em ạ

2021-08-04 16:49 UTC, tvd12 commented on server/freechat-api/src/main/java/com/tvd12/freechat/handler/ChatUserMessageHandler.java
> +		notificationService.notify(chatUserFirebaseTokens,chatMessage);
thiếu khoảng trắng sau dấu phẩy em ạ, nên là: `notificationService.notify(chatUserFirebaseTokens, chatMessage);`

2021-08-04 16:49 UTC, tvd12 commented on server/freechat-api/src/main/java/com/tvd12/freechat/service/impl/FirebaseClient.java
> +package com.tvd12.freechat.service.impl;
anh nghĩa các import này là thừa em ạ

2021-08-04 16:49 UTC, tvd12 commented on server/freechat-api/src/main/java/com/tvd12/freechat/service/impl/FirebaseClient.java
> +package com.tvd12.freechat.service.impl;
À tại sao em lại muốn chuyển gói sáng `impl` em nhỉ? anh thấy để ở service hợp lý hơn đó

2021-08-04 16:49 UTC, tvd12 commented on server/freechat-api/src/main/java/com/tvd12/freechat/service/impl/NotificationServiceImpl.java
>  import java.util.HashMap;
thừa 2 import 

```java
import java.util.HashMap;
import java.util.Map;
```

2021-08-04 16:49 UTC, tvd12 commented on server/freechat-common/src/main/java/com/tvd12/freechat/common/service/impl/ChatUserFirebaseTokenServiceImpl.java
> +        ChatUserFirebaseToken chatUserFirebaseToken =chatUserFirebaseTokenRepo.findByField("username",username);
thiếu dấu cách sau dấu =

2021-08-04 16:49 UTC, tvd12 commented on server/freechat-common/src/main/java/com/tvd12/freechat/common/service/impl/ChatUserFirebaseTokenServiceImpl.java
> +        setUsername.stream().forEach(username->{
thiếu khoảng trắng giữa mũi tên, nên là `username -> {`

2021-08-04 16:49 UTC, tvd12 commented on server/freechat-common/src/main/java/com/tvd12/freechat/common/service/impl/ChatUserFirebaseTokenServiceImpl.java
> +            lstChatUserToken.add(chatUserFirebaseTokenRepo.findByField("username",username));
anh nghĩ là nên viết hàm `findByUsernameIn` chứ không nê dùng vòng for:

```java
@EzyRepository
public interface ChatUserFirebaseTokenRepo extends EzyMongoRepository<String, ChatUserFirebaseToken> {
	
	List<ChatUserFirebaseToken> findByUsernameIn(Set<String> usernames);
	
}
```

2021-08-04 16:49 UTC, tvd12 commented on server/freechat-common/src/main/java/com/tvd12/freechat/common/service/impl/ChatUserFirebaseTokenServiceImpl.java
> +}
thêm dòng trắng ở cuối em nhé

2021-08-09 15:58 UTC, toilahtc96 commented on server/freechat-api/src/main/java/com/tvd12/freechat/handler/ChatUserMessageHandler.java
> +
chỗ này em cần lấy ra đối tượng ChatMessage để xuống dưới call hàm notify anh ạ

2021-08-10 08:47 UTC, tvd12 commented
@toilahtc96 cái này em dùng git bị sai rồi, nó bị lên tận 272 file thay đổi là không đúng rồi em ạ

2021-08-10 14:58 UTC, closed without merging