Features/android config to androidx
youngmonkeys/freechat pull request #22
Opened 2021-07-18 15:46 UTC by toilahtc96

android config to androidx

2021-08-10 15:06 UTC, tvd12 requested changes
PLTAL

2021-08-10 15:06 UTC, tvd12 commented on server/freechat-common/src/main/java/com/tvd12/freechat/common/service/impl/ChatUserFirebaseTokenServiceImpl.java
> +            lstChatUserToken.add(chatUserFirebaseTokenRepo.findByField("username",username));
thêm dẫu cách vào sau dấu phẩy: `findByField("username", username));`

2021-08-10 15:06 UTC, tvd12 commented on server/freechat-common/src/main/java/com/tvd12/freechat/common/service/impl/ChatUserFirebaseTokenServiceImpl.java
> +        Set<ChatUserFirebaseToken> setChatUserFirebaseTokens = lstChatUserToken.stream().collect(Collectors.toSet());
không cần thiết phải chuyển từ list sang set em ạ

2021-08-10 15:06 UTC, tvd12 commented on server/freechat-common/src/main/java/com/tvd12/freechat/common/service/impl/ChatUserFirebaseTokenServiceImpl.java
> +    public Set<ChatUserFirebaseToken> findChatUserFirebaseTokens(Set<String> setUsername) {
cái này em cứ trả về list đi nhé, vì trong database các record đã là duy nhất rồi

2021-08-10 15:06 UTC, tvd12 commented on server/freechat-common/src/main/java/com/tvd12/freechat/common/service/impl/ChatUserFirebaseTokenServiceImpl.java
> +        return chatUserFirebaseToken;
viết luôn thế này em ạ return `chatUserFirebaseTokenRepo.findByField("username", username);`

2021-08-10 15:06 UTC, tvd12 commented on server/freechat-common/src/main/java/com/tvd12/freechat/common/service/impl/ChatUserFirebaseTokenServiceImpl.java
> +        setUsername.stream().forEach(username->{
Em sử dụng `findByUsernameIn` em nhé

2021-08-10 15:06 UTC, tvd12 commented on server/freechat-common/src/main/java/com/tvd12/freechat/common/repo/ChatUserFirebaseTokenRepo.java
> +public interface ChatUserFirebaseTokenRepo extends EzyMongoRepository<String, ChatUserFirebaseToken> {
thêm hàm:

```java
List<ChatUserFirebaseToken> findByUsernameIn(Collection<String> usernames);
```

em ạ
```

2021-08-10 15:08 UTC, toilahtc96 commented on android/app/src/main/AndroidManifest.xml
> +                <!--                <action android:name="android.intent.action.NEW_OUTGOING_CALL"/>-->
cái này theo như em đọc tus là cần anh ạ

2021-08-10 15:20 UTC, tvd12 commented on android/app/src/main/AndroidManifest.xml
> +                <!--                <action android:name="android.intent.action.NEW_OUTGOING_CALL"/>-->
anh thấy em comment đi, vậy tức là vẫn cần bỏ comment đúng ko em?

2021-08-15 13:41 UTC, tvd12 commented
@toilahtc96 anh vừa merge master vào `android-push-notification`, giờ em giúp anh các bước sau nhé:

1. `git checkout android-push-notification`
2. `git pull https://github.com/youngmonkeys/freechat.git android-push-notification`
2. `git checkout features/android-config-to-androidx`
3. `git merge android-push-notification`
4.  fix conflict
5.  `git commit -am 'merge android-push-notification`
6. `git push origin features/android-config-to-androidx` 

Nhé

2021-08-15 16:11 UTC, tvd12 requested changes
@toilahtc96 PLTAL

2021-08-15 16:11 UTC, tvd12 commented on android/app/build.gradle
> +    implementation 'com.google.firebase:firebase-auth-ktx'
tại sao 2 cái này thiếu version em nhỉ?

2021-08-15 16:11 UTC, tvd12 commented on android/app/src/main/AndroidManifest.xml
>  </manifest>
thêm 1 dòng trắng cho nó em nhé

2021-08-15 16:11 UTC, tvd12 commented on android/app/src/main/java/com/tvd12/freechat/firebase/cloud/message/MyFirebaseMessagingService.kt
> +package com.tvd12.freechat.firebase.cloud.message
em chỉ cần để tên gói là `com.tvd12.freechat.firebase` là được em ạ

2021-08-15 16:11 UTC, tvd12 commented on android/app/src/main/java/com/tvd12/freechat/firebase/cloud/message/MyFirebaseMessagingService.kt
> +class MyFirebaseMessagingService : FirebaseMessagingService() {
1. nó phải là public class đúng không em?
2. Tên lớp không nên để là Myxxx em có thể đổi thành `ChatFirebaseMessagingService` em nhé

2021-08-15 16:11 UTC, tvd12 commented on android/app/src/main/java/com/tvd12/freechat/firebase/cloud/message/MyFirebaseMessagingService.kt
> +        val imgSett = prefs.getString("fb", "");
cái này thừa đúng không em?

2021-08-15 16:11 UTC, tvd12 commented on android/app/src/main/java/com/tvd12/freechat/firebase/cloud/message/MyFirebaseMessagingService.kt
> +
thừa dòng trắng em ạ

2021-08-15 16:11 UTC, tvd12 commented on android/app/src/main/java/com/tvd12/freechat/firebase/cloud/message/MyFirebaseMessagingService.kt
> +    }
hàm này không cần thiết nếu chỉ gọ lớp cha em ạ

2021-08-15 16:11 UTC, tvd12 commented on android/app/src/main/java/com/tvd12/freechat/firebase/cloud/message/MyFirebaseMessagingService.kt
> +import com.tvd12.freechat.MainActivity
bỏ các import thừa em nhé

2021-08-15 16:11 UTC, tvd12 commented on android/app/src/main/java/com/tvd12/freechat/firebase/cloud/message/MyFirebaseMessagingService.kt
> +        Log.d("newToken", token);
phải là thế này em ạ: `Log.d(Constants.TAG, "new firebase token generated: $token")`

2021-08-15 16:11 UTC, tvd12 commented on android/app/src/main/java/com/tvd12/freechat/firebase/cloud/message/MyFirebaseMessagingService.kt
> +        getSharedPreferences("_", MODE_PRIVATE).edit().putString("fb", token).apply();
chỗ này em nên tạo 1 hàm storeToken để rõ nghĩ rồi gọi em ạ:

```kotlin
private fun storeToken(token: String) {
        getSharedPreferences("_", MODE_PRIVATE)
            .edit()
            .putString("fb", token)
            .apply();
    }
```

sử dụng:

```
storeToken(token)
```

2021-08-15 16:11 UTC, tvd12 commented on android/gradle.properties
> +android.enableJetifier=true
thêm dòng trắng cho nó em nhé

2021-08-19 10:16 UTC, toilahtc96 commented on android/app/build.gradle
> +    implementation 'com.google.firebase:firebase-auth-ktx'
cái này em làm theo tus nên cũng k hiểu là thiếu gì anh ạ.

2021-08-20 08:23 UTC, tvd12 requested changes

2021-08-20 08:23 UTC, tvd12 commented on android/app/src/main/java/com/tvd12/freechat/firebase/MyFirebaseMessagingService.kt
> +        getSharedPreferences("_", MODE_PRIVATE).edit().putString("fb", token).apply();
chỗ này thừa em ạ

2021-08-20 08:51 UTC, tvd12 approved these changes
LGTM

2021-08-20 08:52 UTC, merged